### ISSUE TITLE
您好，请问怎么设置单双声道呢？默认就是单声道？另外采样率可以是16000吗，我设置了录出来不正确。

### ISSUE THREAD

**Issue by RenqiangZone** [jiwenjiang/react-audio-analyser#1]
您好，请问怎么设置单双声道呢？默认就是单声道？另外采样率可以是16000吗，我设置了录出来不正确。

谢谢！

**Comment by jiwenjiang** [comment]
声道是根据你输入音频的信息获取的，[https://github.com/jiwenjiang/react-audio-analyser/blob/master/src/component/AudioAnalyser/audioConvertWav.js#L6](url)，采样率可以设置16000，你指的不正确是什么，采样率设置16000之后，音频会变慢变低是正常的。

**Comment by RenqiangZone** [comment]
好的，谢谢。

采样率设置为16000，音频应该是变慢变低了，就是录出来的声音完全不是正常的音频，很模糊，听不清说的什么。
