### ISSUE TITLE
音频波没有正常波动

### ISSUE THREAD

**Issue by momo9488** [jiwenjiang/react-audio-analyser#10]
在一次录音完成之后，开始下一次录音的时候，音频波没有正常的波动

**Comment by momo9488** [comment]
发现一些细节：1、火狐上音频波是正常的。2、谷歌音频波在重新录音的时候是不正常的。3、safari上不支持录音功能

**Comment by jiwenjiang** [comment]
好的。昨天我看了一下，感觉是audio上下文，在暂停后，音频缓冲数组断开连接了，以前是不会的，我今天尝试下重新初始化或者重连一下音频上下文。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: momo9488 <notifications@github.com&gt;
发送时间: 2019年10月31日 10:26
收件人: jiwenjiang/react-audio-analyser <react-audio-analyser@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[jiwenjiang/react-audio-analyser] 音频波没有正常波动 (#10)

**Comment by jiwenjiang** [comment]
> 发现一些细节：1、火狐上音频波是正常的。2、谷歌音频波在重新录音的时候是不正常的。3、safari上不支持录音功能

已经改好了。在开始和恢复录音后，重新初始化了音频上下文的analyser，目前谷歌浏览器测试已经可以了。代码仓库和npm已经更新

**Comment by jiwenjiang** [comment]
谷歌，火狐均以测试。

**Comment by momo9488** [comment]
好，非常感谢❤


 
---原始邮件---
发件人: "j_bleach"<notifications@github.com&gt;
发送时间: 2019年10月31日 15:42:27
收件人: "jiwenjiang/react-audio-analyser"<react-audio-analyser@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"momo9488"<960587842@qq.com&gt;;
主题: Re: [jiwenjiang/react-audio-analyser] 音频波没有正常波动 (#10)



谷歌，火狐均以测试。
