### ISSUE TITLE
手机录音报错啊

### ISSUE THREAD

**Issue by zzfenglove** [jiwenjiang/react-audio-analyser#18]
手机上录音报错啊

**Comment by jiwenjiang** [comment]
safari 目前不行



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zhangfeng <notifications@github.com&gt;
发送时间: 2019年11月2日 18:52
收件人: jiwenjiang/react-audio-analyser <react-audio-analyser@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[jiwenjiang/react-audio-analyser] 手机录音报错啊 (#18)




手机上录音报错啊
