### ISSUE TITLE
Error when install on a next project 

### ISSUE THREAD

**Issue by romain130492** [jiwenjiang/react-audio-analyser#19]
Any ideas why i get this error ? 

thanks

Client pings, but there's no entry for page: /_error
/App_Next_reactStrapV2/node_modules/react-audio-analyser/lib/index.js:4
import AudioAnalyser from './AudioAnalyser';
       ^^^^^^^^^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:80:7)
    at createScript (vm.js:274:10)
    at Object.runInThisContext (vm.js:326:10)

**Comment by jiwenjiang** [comment]
> Any ideas why i get this error ?
> 
> thanks
> 
> Client pings, but there's no entry for page: /_error
> /App_Next_reactStrapV2/node_modules/react-audio-analyser/lib/index.js:4
> import AudioAnalyser from './AudioAnalyser';
> ^^^^^^^^^^^^^
> 
> SyntaxError: Unexpected identifier
> at new Script (vm.js:80:7)
> at createScript (vm.js:274:10)
> at Object.runInThisContext (vm.js:326:10)

sry...I have not encountered this situation. It works fine on v0.2.6.

**Comment by bshahrok** [comment]
I have the same problem when I try to test. Did you manage to resolve this?

> Any ideas why i get this error ?
> 
> thanks
> 
> Client pings, but there's no entry for page: /_error
> /App_Next_reactStrapV2/node_modules/react-audio-analyser/lib/index.js:4
> import AudioAnalyser from './AudioAnalyser';
> ^^^^^^^^^^^^^
> 
> SyntaxError: Unexpected identifier
> at new Script (vm.js:80:7)
> at createScript (vm.js:274:10)
> at Object.runInThisContext (vm.js:326:10)
