### ISSUE TITLE
Can't resolve './webWorker'

### ISSUE THREAD

**Issue by wentao978** [jiwenjiang/react-audio-analyser#2]

**Comment by jiwenjiang** [comment]
> _No description provided._

已修复

**Comment by wentao978** [comment]
谢谢，还有一个问题，用百度云的sdk解码一直报错
3301 错误
识别结果实际为空。可能是音频质量过差，不清晰，或者是空白音频。 有时也可能是pcm填错采样率。如16K采样率的pcm文件，填写的rate参数为8000。
“修改了demo/index.js line:30  // audioOptions: {sampleRate: 30000}, // 设置输出音频采样率 ”，然后录音文件声音太粗了，是根据声道数和采样率有关吗？

**Comment by jiwenjiang** [comment]
声道数是确定的，采样率越低音频信息越少，这些是可以不设置的，走默认就好

**Comment by wentao978** [comment]
嗯，通过AudioBuffer看到，声道numberOfChannels: 1, 采样率sampleRate: 44100，默认是这些配置，可是百度云那边的采样率《

3311 | 用户输入错误 | 采样率rate参数不在选项里 | 目前rate参数仅提供8000,16000两种，填写4000即会有此错误
-- | -- | -- | --


》
能不能帮忙看看这个要怎么处理才合适呢？

**Comment by jiwenjiang** [comment]
这个没有接触过。。可能解答不了你了，不好意思。。

**Comment by wentao978** [comment]
嗯，我那我再查查，谢啦~
