### ISSUE TITLE
录制时长问题

### ISSUE THREAD

**Issue by wukaMM** [jiwenjiang/react-audio-analyser#20]
大神你好，想问下，如何在录制的过程中同时获取已经录制的时长秒数呢？

**Comment by jiwenjiang** [comment]
这个你自己在开启录制的方法中获取当前时间，然后停止录制时，再用结束时的当前的时间减去开始的时间就可以了。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: wukaMM <notifications@github.com&gt;
发送时间: 2019年11月14日 18:48
收件人: jiwenjiang/react-audio-analyser <react-audio-analyser@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[jiwenjiang/react-audio-analyser] 录制时长问题 (#20)




大神你好，想问下，如何在录制的过程中同时获取已经录制的时长秒数呢？

**Comment by wukaMM** [comment]
回复的太快啦！感谢~~~
不过这个时间的话会包含中间暂停时长，刚看到了timeslice 这个参数，把这个参数设置成1s的话，每次在onRecordCallback 里面加1s，这样可以吗，会不会有误差呢

**Comment by jiwenjiang** [comment]
误差不会太大，可以这样累计。或者你也可以在暂停的时候把阶段时间算出来，然后恢复的时候重新计时。最后把整个时间算出来



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: wukaMM <notifications@github.com&gt;
发送时间: 2019年11月14日 19:12
收件人: jiwenjiang/react-audio-analyser <react-audio-analyser@noreply.github.com&gt;
抄送: j_bleach <513755565@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[jiwenjiang/react-audio-analyser] 录制时长问题 (#20)




回复的太快啦！感谢~~~
 不过这个时间的话会包含中间暂停时长，刚看到了timeslice 这个参数，把这个参数设置成1s的话，每次在onRecordCallback 里面加1s，这样可以吗，会不会有误差呢

**Comment by wukaMM** [comment]
恩恩，感谢~~~
还想问下，如果想调节音频曲线的样式和速度的话，现在有什么办法吗？比如想要像 siri 那种样式
![1573730902979](https://user-images.githubusercontent.com/1595115/68853438-f2a71d00-0714-11ea-946a-2fb62c5ad176.jpg)

**Comment by jiwenjiang** [comment]
这个你只能去改我的源码了，在rendercavas 那个里面。有一个buffer array 会有一个区间数组可以操作。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: wukaMM <notifications@github.com&gt;
发送时间: 2019年11月14日 19:28
收件人: jiwenjiang/react-audio-analyser <react-audio-analyser@noreply.github.com&gt;
抄送: j_bleach <513755565@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[jiwenjiang/react-audio-analyser] 录制时长问题 (#20)




恩恩，感谢~~~
 还想问下，如果想调节音频曲线的样式和速度的话，现在有什么办法吗？比如想要像 siri 那种样式

**Comment by wukaMM** [comment]
恩恩，好的，那我再看看，谢谢大神指点😊
