### ISSUE TITLE
生产环境 Cannot read property 'errorCallback' of undefined

### ISSUE THREAD

**Issue by wukaMM** [jiwenjiang/react-audio-analyser#21]
大神，在本地测试的时候，都是很正常的，但是上到生产环境后，点击开始录音，就一直报这个错误，请问大神知道可能是什么导致的吗？
![1575001933899](https://user-images.githubusercontent.com/1595115/69843879-5b110500-12a4-11ea-8490-d2b3a89d97e1.jpg)

**Comment by jiwenjiang** [comment]
这个是你在自己程序里面写的errorback吗，可否提供更完整一点的代码。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: wukaMM <notifications@github.com&gt;
发送时间: 2019年11月29日 12:32
收件人: jiwenjiang/react-audio-analyser <react-audio-analyser@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[jiwenjiang/react-audio-analyser] 生产环境 Cannot read property 'errorCallback' of undefined (#21)




大神，在本地测试的时候，都是很正常的，但是上到生产环境后，点击开始录音，就一直报这个错误，请问大神知道可能是什么导致的吗？

**Comment by wukaMM** [comment]
这个是仿照你前面的示例代码写的
const audioProps = {
      status,
      backgroundColor: '#fff',
      strokeColor: '#0060FF',
      width: 216,
      height: 40,
      audioOptions: {
        type: 'audio/mp3'
      },
      audioBitsPerSecond: 128000,
      timeslice: 1000,
      startCallback: (e) => {},
      pauseCallback: (e) => {},
      stopCallback: (e) => {},
      onRecordCallback: (e) => {
        this.setState({
          period: period + 1
        })
      },
      errorCallback: (err) => {
        message.error(err);
      }
    };
只有这个地方有 errorCallback

**Comment by wukaMM** [comment]
不好意思啊，这个代码这么粘贴出来连缩进都没有了[Facepalm]

**Comment by alokupadhya** [comment]
Got same error

**Comment by alokupadhya** [comment]
![Screenshot from 2020-07-29 13-46-58](https://user-images.githubusercontent.com/25848465/88775459-5b9acc00-d1a2-11ea-9acd-0ce299371e28.png)

**Comment by alokupadhya** [comment]
Problem solved by switching http to https

**Comment by PragunSaini** [comment]
Did you find the cause of this error?

**Comment by jiwenjiang** [comment]
not yet



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Pragun Saini <notifications@github.com&gt;
发送时间: 2020年8月19日 19:41
收件人: jiwenjiang/react-audio-analyser <react-audio-analyser@noreply.github.com&gt;
抄送: j_bleach <513755565@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[jiwenjiang/react-audio-analyser] 生产环境 Cannot read property 'errorCallback' of undefined (#21)





 
Did you find the cause of this error?

**Comment by alokupadhya** [comment]
> Did you find the cause of this error?

because mic access required a secure connection (https).

**Comment by jiwenjiang** [comment]
生产环境 需要https
