### ISSUE TITLE
当页面上同时有多个AudioAnalyser组件时，波只会显示在其中一个组件上。

### ISSUE THREAD

**Issue by liust97** [jiwenjiang/react-audio-analyser#22]
![image](https://user-images.githubusercontent.com/30302600/71325676-e006cd00-24a4-11ea-91bb-498fef0c79f9.png)
页面上同时有两个AudioAnalyser组件，使用左边的组件，但波显示在了右边的组件上。

**Comment by jiwenjiang** [comment]
确实存在这个问题，会在下一个版本修复。

**Comment by jiwenjiang** [comment]
> ![image](https://user-images.githubusercontent.com/30302600/71325676-e006cd00-24a4-11ea-91bb-498fef0c79f9.png)
> 页面上同时有两个AudioAnalyser组件，使用左边的组件，但波显示在了右边的组件上。

在v0.3.0版本已修复多个组件的隔离问题 @liust97
