### ISSUE TITLE
The AudioContext was not allowed to start.

### ISSUE THREAD

**Issue by xym4869** [jiwenjiang/react-audio-analyser#26]
![image](https://user-images.githubusercontent.com/20354627/87745606-f7cae780-c820-11ea-95c6-65a4ad12500e.png)
The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page.

请问这个问题怎么解决？

**Comment by jiwenjiang** [comment]
错误提示必须通过用户行为播放



发自我的iPhone


------------------ Original ------------------

**Comment by xym4869** [comment]
请问如何修改呢？并没有跳出通知开启麦克风的通知

发自我的iPhone

**Comment by jiwenjiang** [comment]
修改浏览器配置，参考一下https://blog.csdn.net/L95_0719/article/details/102727666
