### ISSUE TITLE
点击stop后，网页端麦克风没有关闭的问题

### ISSUE THREAD

**Issue by xym4869** [jiwenjiang/react-audio-analyser#29]
![](https://user-images.githubusercontent.com/20354627/89877193-543bdf80-dbf2-11ea-9cec-3e7a56485eb4.png)
左上角红点点在点击stop以后还有。请问可以点击stop后关闭麦克风吗？

**Comment by hange1223** [comment]
点击停止后 ，只是停止录音了，但是没走stopCallback这个方法啊

**Comment by hange1223** [comment]
解决了 是因为audioType初始化为空，给个默认值就行了
