### ISSUE TITLE
Still WaveForm Canvas after pressing Stop

### ISSUE THREAD

**Issue by qpixHassaballah** [jiwenjiang/react-audio-analyser#7]
After I press stop the canvas returns back to default .
Can the canvas view the recorded audio wave form ?
and how ?

**Comment by jiwenjiang** [comment]
The audio wave replay is not supported, and can be considered later.

**Comment by qpixHassaballah** [comment]
Can i have any idea on how can i do it myself i am currently observing the RenderCanvas.js file how can i store the data Array into a larger array and then plot this array on canvas ??

**Comment by jiwenjiang** [comment]
Sry, I was busy a few days ago. let me have a try

**Comment by iamarasekera** [comment]
How can I modify  this source code to download the audio clip in wav form?

**Comment by momo9488** [comment]
你好，按下停止后，重新录音，音频波就不能正常的波动了。请问这个要怎么解决

**Comment by jiwenjiang** [comment]
有报错吗




------------------ 原始邮件 ------------------
发件人: "momo9488"<notifications@github.com>; 
发送时间: 2019年10月29日(星期二) 下午2:52
收件人: "jiwenjiang/react-audio-analyser"<react-audio-analyser@noreply.github.com>; 
抄送: "bleach"<513755565@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [jiwenjiang/react-audio-analyser] Still WaveForm Canvas afterpressing Stop (#7)




你好，按下停止后，重新录音，音频波就不能正常的波动了。请问这个要怎么解决

**Comment by momo9488** [comment]
没有报错，但是音频波不动了


 
---Original---

**Comment by jiwenjiang** [comment]
确实现在有这个问题，麻烦你提个issue吧，我有空改下



发自我的iPhone


------------------ Original ------------------

**Comment by momo9488** [comment]
好，已经提了issues，希望能得到您的帮助，非常感谢


 
---Original---
